// ============================================================
// ZLinke 智链 — AI工具分类体系 v2
// 8个一级分类，覆盖主流AI工具场景
// ============================================================

// 一级分类（用于页面筛选导航）
export const categories = [
  '全部',
  'AI对话助手',
  'AI写作工具',
  'AI编程开发',
  'AI图像生成',
  'AI视频创作',
  'AI办公效率',
  'AI搜索工具',
  'AI音乐音频',
  'AI工作台',
] as const

export interface Tool {
  id: string
  name: string
  description: string
  category: string       // 一级分类
  subCategory?: string   // 二级分类（可选，用于更细粒度分组）
  rating: number
  url: string
  price: string
  features: string[]     // 功能标签
}

export const tools: Tool[] = [
  // ========================
  // 一、AI对话助手
  // ========================
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI推出的AI对话助手，支持文本生成、代码编写、图像理解等多种能力，是目前使用最广泛的AI工具。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.8,
    url: 'https://chat.openai.com',
    price: '免费 / Plus $20/月',
    features: ['文本生成', '代码编写', '图像理解', '插件生态'],
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Anthropic推出的AI助手，在长文本处理和逻辑推理方面表现突出，特别适合学术写作和代码分析。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.7,
    url: 'https://claude.ai',
    price: '免费 / Pro $20/月',
    features: ['长文本处理', '逻辑推理', '学术写作', '代码分析'],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google推出的多模态AI助手，原生支持文本、图像、音频、视频理解，与Google生态深度整合。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.5,
    url: 'https://gemini.google.com',
    price: '免费 / Advanced $18/月',
    features: ['多模态理解', 'Google生态', '长上下文', '文件分析'],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    description: '月之暗面推出的国产AI助手，以超长上下文处理能力著称，可一次性处理20万字以上的内容。',
    category: 'AI对话助手',
    subCategory: '国产助手',
    rating: 4.5,
    url: 'https://kimi.moonshot.cn',
    price: '免费',
    features: ['超长上下文', '文件处理', '联网搜索', '中文优化'],
  },
  {
    id: 'doubao',
    name: '豆包',
    description: '字节跳动推出的AI对话助手，集成在抖音、今日头条等产品中，支持多种创作场景。',
    category: 'AI对话助手',
    subCategory: '国产助手',
    rating: 4.3,
    url: 'https://www.doubao.com',
    price: '免费',
    features: ['中文对话', '内容创作', '多端同步', '语音交互'],
  },
  {
    id: 'coze',
    name: 'Coze（扣子）',
    description: '字节跳动推出的AI Bot搭建平台，无需编程即可创建自定义AI助手，支持发布到多个平台。',
    category: 'AI对话助手',
    subCategory: 'Bot搭建',
    rating: 4.4,
    url: 'https://www.coze.com',
    price: '免费',
    features: ['Bot搭建', '工作流编排', '知识库', '多平台发布'],
  },
  {
    id: 'poe',
    name: 'Poe',
    description: 'Quora推出的AI模型聚合平台，在一个界面中访问ChatGPT、Claude、Gemini等主流模型，支持自定义Bot。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.3,
    url: 'https://poe.com',
    price: '免费 / Pro $19.99/月',
    features: ['多模型聚合', '自定义Bot', '跨模型对比', '知识库'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek（深度求索）',
    description: '国产开源AI大模型标杆，V4版本推理性能世界顶级，Agent能力大幅提升，支持网页/App/API三端使用。',
    category: 'AI对话助手',
    subCategory: '国产助手',
    rating: 4.8,
    url: 'https://www.deepseek.com',
    price: '免费 / API按量付费',
    features: ['开源模型', '超强推理', 'Agent能力', '代码生成'],
  },
  {
    id: 'typingmind',
    name: 'TypingMind',
    description: '最佳LLM聚合聊天前端，自带API Key即可同时使用ChatGPT、Claude、Gemini等主流模型，买断制无月费，支持插件生态和AI Agent构建。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.4,
    url: 'https://typingmind.com',
    price: '买断制 $39起 / 自带API Key',
    features: ['多模型聚合', '自带APIKey', '买断制', '插件生态'],
  },
  {
    id: 'discode-ai',
    name: 'discode.ai',
    description: '100+ AI模型聚合平台，智能选择最佳模型回答每个问题，独创CO₂足迹追踪、本地敏感数据检测和数据匿名化，支持多模型幻觉交叉检查。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.2,
    url: 'https://discode.ai',
    price: '免费 / Pro定价联系官方',
    features: ['100+模型聚合', '智能模型选择', 'CO₂可持续追踪', '多模型幻觉检查'],
  },
  {
    id: 'asi-one',
    name: 'ASI:One',
    description: 'Fetch.ai打造的个人AI助手，具备短/中/长期记忆，可学习用户偏好并与其他AI协作、自动规划执行任务，连接Agentverse数百万智能体。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.0,
    url: 'https://asi1.ai',
    price: '免费 / 付费方案联系官方',
    features: ['长期记忆', 'AI协作规划', 'Agentverse生态', '个性化人格'],
  },
  {
    id: 'osaurus',
    name: 'Osaurus',
    description: 'macOS原生本地AI助手，模型完全在Apple Silicon芯片上离线运行，支持自建模Agent、共享记忆与MCP，数据不出本机。',
    category: 'AI对话助手',
    subCategory: '通用助手',
    rating: 4.2,
    url: 'https://osaurus.ai',
    price: '免费（开源 MIT）',
    features: ['本地离线运行', '自建Agent', '共享记忆', 'MCP服务器'],
  },

  // ========================
  // 二、AI写作工具
  // ========================
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'Notion内置的AI写作助手，支持摘要、翻译、头脑风暴、改写等功能，知识管理工作流的神器。',
    category: 'AI写作工具',
    subCategory: 'AI辅助写作',
    rating: 4.4,
    url: 'https://www.notion.so',
    price: '免费 / Plus $10/月',
    features: ['智能摘要', '翻译润色', '头脑风暴', '知识管理'],
  },
  {
    id: 'jasper',
    name: 'Jasper AI',
    description: '专注营销内容创作的AI写作平台，支持博客、社交媒体、广告文案等多种内容类型，团队协作强大。',
    category: 'AI写作工具',
    subCategory: '营销文案',
    rating: 4.2,
    url: 'https://www.jasper.ai',
    price: '$49/月起',
    features: ['营销文案', '博客生成', '品牌语调', '多语言'],
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: '全球最受欢迎的AI写作助手，专注英文语法检查、润色和风格优化，支持全平台集成。',
    category: 'AI写作工具',
    subCategory: '英文写作',
    rating: 4.5,
    url: 'https://www.grammarly.com',
    price: '免费 / Premium $12/月',
    features: ['语法检查', '风格优化', '查重检测', '全平台集成'],
  },
  {
    id: 'xiezuocat',
    name: '写作猫',
    description: '秘塔科技推出的AI中文写作助手，专注学术写作和长文生成，支持论文大纲和全文生成。',
    category: 'AI写作工具',
    subCategory: '中文写作',
    rating: 4.1,
    url: 'https://xiezuocat.com',
    price: '免费 / Pro ¥59/月',
    features: ['中文写作', '学术论文', '大纲生成', '续写改写'],
  },

  // ========================
  // 三、AI编程开发
  // ========================
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI驱动的代码编辑器，内置AI补全和对话功能，支持Claude和GPT-4等多模型，开发者效率提升利器。',
    category: 'AI编程开发',
    subCategory: 'AI编辑器',
    rating: 4.7,
    url: 'https://cursor.sh',
    price: '免费 / Pro $20/月',
    features: ['AI代码补全', '对话式编程', '多模型支持', '代码重构'],
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    description: '微软推出的AI编程助手，深度集成VS Code等编辑器，支持代码补全、解释和测试生成。',
    category: 'AI编程开发',
    subCategory: 'AI编辑器',
    rating: 4.5,
    url: 'https://github.com/features/copilot',
    price: '免费 / Individual $10/月',
    features: ['实时代码补全', '多编辑器支持', '代码解释', '测试生成'],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    description: 'Codeium推出的AI原生IDE，首创Flow模式实现Agent式编程，理解项目上下文自动完成复杂任务。',
    category: 'AI编程开发',
    subCategory: 'AI编辑器',
    rating: 4.4,
    url: 'https://codeium.com/windsurf',
    price: '免费 / Pro $15/月',
    features: ['Flow模式', '项目理解', '多文件编辑', '终端集成'],
  },
  {
    id: 'replit',
    name: 'Replit',
    description: '云端AI开发平台，浏览器内即可编写、运行和部署应用，内置AI编程助手GhostWriter。',
    category: 'AI编程开发',
    subCategory: '云端开发',
    rating: 4.3,
    url: 'https://replit.com',
    price: '免费 / Pro $20/月',
    features: ['云端IDE', '即时部署', '协作编辑', 'GhostWriter'],
  },
  {
    id: 'bolt-new',
    name: 'Bolt.new',
    description: 'StackBlitz推出的浏览器内全栈AI应用构建工具，WebContainer技术让完整Node.js环境直接在浏览器运行，从自然语言到可部署Web应用仅需几分钟。',
    category: 'AI编程开发',
    subCategory: '云端开发',
    rating: 4.3,
    url: 'https://bolt.new',
    price: '免费 / Pro $25/月',
    features: ['浏览器全栈运行时', 'Bolt Cloud后端一体化', 'Bolt v2自主调试', 'MCP连接器', 'Figma导入'],
  },
  {
    id: 'coderabbit',
    name: 'CodeRabbit',
    description: '全球安装量最大的AI代码审查工具，自动审查PR并发现缺陷，支持GitHub/GitLab/Bitbucket，被NVIDIA等15000+企业采用。',
    category: 'AI编程开发',
    subCategory: 'AI代码审查',
    rating: 4.5,
    url: 'https://www.coderabbit.ai',
    price: '免费 / Pro $24/月 / Pro+ $48/月',
    features: ['PR自动审查', '40+扫描层', 'Learnings学习', '全4大Git平台', '开源永久免费'],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    description: '开源AI编程代理标杆，160K+ GitHub Star，登顶LogRocket 2026年6月AI开发工具实力榜第一，支持75+模型和任意编辑器。',
    category: 'AI编程开发',
    subCategory: 'AI编辑器',
    rating: 4.6,
    url: 'https://opencode.ai',
    price: '免费开源 / Go $10月 / Zen按量',
    features: ['开源免费', '多模型支持', '终端+IDE+桌面', 'LSP智能集成'],
  },
  {
    id: 'swytchcode',
    name: 'Swytchcode',
    description: 'AI代理API执行层，为Cursor/Claude等AI编码助手提供可靠的API调用运行时，自动处理认证、重试和策略控制，覆盖2000+ API。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://www.swytchcode.com',
    price: '免费 / Pro $29/月',
    features: ['API执行层', '策略控制', '2000+集成', 'MCP支持'],
  },
  {
    id: 'vokal',
    name: 'Vokal',
    description: 'AI Agent协作工作空间，让团队与AI Agent在共享频道中协作开发，支持Claude Code/Codex/Cursor等，20+预设角色，Product Hunt日榜第2名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://vokal.team',
    price: '免费 / 付费方案联系官方',
    features: ['Agent协作空间', '多Agent管理', '共享上下文', '20+预设角色'],
  },
  {
    id: 'browserbase',
    name: 'Browserbase',
    description: '为AI Agent提供可靠的Web自动化基础设施，让Agent像人类一样浏览和操作网页，10,000+企业使用，Product Hunt日榜第2名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://browserbase.com',
    price: '免费 / 按量付费',
    features: ['浏览器自动化', 'Agent Web访问', 'Search API', 'Fetch API'],
  },

  // ========================
  // 四、AI图像生成
  // ========================
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: '顶级AI绘画工具，通过Discord使用，以卓越的艺术风格和美学表现力著称，深受设计师喜爱。',
    category: 'AI图像生成',
    subCategory: 'AI绘画',
    rating: 4.6,
    url: 'https://midjourney.com',
    price: '$10/月起',
    features: ['高质量出图', '艺术风格', '图片变体', '社区灵感'],
  },
  {
    id: 'dalle3',
    name: 'DALL·E 3',
    description: 'OpenAI推出的AI图像生成模型，集成在ChatGPT Plus中，以精准的文字理解和高质量输出见长。',
    category: 'AI图像生成',
    subCategory: 'AI绘画',
    rating: 4.4,
    url: 'https://openai.com/dall-e-3',
    price: 'ChatGPT Plus $20/月',
    features: ['文字理解', '高质量输出', 'ChatGPT集成', '编辑修复'],
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: '开源AI绘画模型，支持本地部署和完全自定义，隐私安全，社区生态丰富。',
    category: 'AI图像生成',
    subCategory: 'AI绘画',
    rating: 4.3,
    url: 'https://stability.ai',
    price: '免费（开源）',
    features: ['开源免费', '本地部署', '高度自定义', '模型丰富'],
  },
  {
    id: 'canva-ai',
    name: 'Canva AI',
    description: 'Canva内置的AI设计功能，支持一键生成设计模板、AI图片编辑和品牌套件，设计小白也能出大片。',
    category: 'AI图像生成',
    subCategory: 'AI设计',
    rating: 4.5,
    url: 'https://www.canva.com',
    price: '免费 / Pro $13/月',
    features: ['AI设计生成', '模板库', '品牌套件', '团队协作'],
  },
  {
    id: 'leonardo',
    name: 'Leonardo.ai',
    description: '专业的AI图像生成平台，提供丰富的模型选择和精细控制参数，适合游戏素材和概念设计。',
    category: 'AI图像生成',
    subCategory: 'AI绘画',
    rating: 4.3,
    url: 'https://leonardo.ai',
    price: '免费 / Pro $10/月',
    features: ['模型丰富', '精细控制', '游戏素材', '训练模型'],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: '文字渲染最强的AI图像生成工具，支持在图片中精准嵌入文字，适合Logo、海报和社媒素材设计。',
    category: 'AI图像生成',
    subCategory: 'AI绘画',
    rating: 4.3,
    url: 'https://ideogram.ai',
    price: '免费 / Plus $20月 / Pro $60月',
    features: ['文字渲染', '高质量出图', '风格多样', '创意设计'],
  },
  {
    id: 'openart',
    name: 'OpenArt',
    description: '800万+月活用户的AI全栈创作平台，集图像生成、对话式导演（Director，一键产出最长约5分钟成片）、角色一致性、3D世界构建于一体，支持Sora 2/Kling 3.0/Seedance 2.0等100+模型，2025年ARR约$7000万、已盈利。',
    category: 'AI图像生成',
    subCategory: 'AI绘画',
    rating: 4.3,
    url: 'https://openart.ai',
    price: '免费 / Essential $14/月起',
    features: ['AI图像+视频', '角色一致性', 'Vibe Direct导演模式', '100+模型聚合'],
  },
  {
    id: 'zawa',
    name: 'Zawa',
    description: 'AI品牌创意Agent平台（原X-Design），一键生成Logo/海报/社媒素材/产品图，支持AI产品摄影和视频生成，全新Image Remix功能可克隆热门图片构图并替换自家产品，GlobeNewswire 7月3日报道。',
    category: 'AI图像生成',
    subCategory: 'AI设计',
    rating: 4.2,
    url: 'https://zawa.ai',
    price: '免费 / 付费方案',
    features: ['AI品牌设计', 'Logo生成', '图像翻拍', '社媒素材'],
  },

  // ========================
  // 五、AI视频创作
  // ========================
  {
    id: 'runway',
    name: 'Runway Gen-3',
    description: '领先的AI视频生成平台，支持文生视频、图生视频、视频编辑等多种功能，好莱坞级别的创作工具。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.5,
    url: 'https://runwayml.com',
    price: '免费 / Pro $15/月',
    features: ['文生视频', '图生视频', '视频编辑', '绿幕抠像'],
  },
  {
    id: 'pika',
    name: 'Pika',
    description: '新一代AI视频生成工具，操作简单，支持视频修改、扩展和风格转换，适合快速创作社交内容。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.2,
    url: 'https://pika.art',
    price: '免费 / Pro $10/月',
    features: ['视频生成', '视频修改', '风格转换', '社交分享'],
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'AI数字人视频生成平台，上传文字即可生成逼真的数字人播报视频，支持多语言和多数字人形象。',
    category: 'AI视频创作',
    subCategory: '数字人',
    rating: 4.4,
    url: 'https://www.heygen.com',
    price: '免费 / Pro $24/月',
    features: ['数字人生成', '多语言', '口型同步', '模板丰富'],
  },
  {
    id: 'kling-ai',
    name: 'Kling AI（可灵）',
    description: '快手推出的专业AI视频生成工具，支持文生视频、图生视频，电影级画质，国内AI视频标杆产品。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.5,
    url: 'https://klingai.com',
    price: '免费 / Pro ¥66/月',
    features: ['文生视频', '图生视频', '电影画质', '多镜头编辑'],
  },
  {
    id: 'vaani',
    name: 'Vaani',
    description: 'AI口型同步配音平台，支持40+语言的视频本地化，保留原声语调与节奏，唇形精准同步，创作者/品牌/工作室的专业级AI配音工具。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.2,
    url: 'https://vaani.media',
    price: '免费试用 / $49/月起',
    features: ['口型同步配音', '40+语言', '声音克隆', '广播级混音'],
  },
  {
    id: 'autoedit',
    name: 'AutoEdit',
    description: 'Claude AI驱动的Premiere Pro智能剪辑插件，自动移除静音、语气词和NG镜头，生成字幕，15,000+剪辑师使用，Trustpilot评分4.67，将粗剪效率提升10倍。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.3,
    url: 'https://www.autoeditai.net',
    price: '免费试用 / $29/月起',
    features: ['AI自动剪辑', '智能静音移除', '99+语言字幕', 'Claude AI驱动'],
  },
  {
    id: 'vebeai',
    name: 'VebeAI',
    description: 'AI短视频生产工作空间，将想法/链接/文件/音频转为可编辑视频草稿，AI自动生成脚本、场景、字幕和节奏规划，支持TikTok/Reels/Shorts/广告多格式导出。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.1,
    url: 'https://vebe.ai',
    price: '免费 / Pro定价待公布',
    features: ['多源生成视频', 'AI脚本+场景+字幕', '多模型支持', '团队协作工作空间'],
  },
  {
    id: 'ciaro-pro',
    name: 'Ciaro Pro',
    description: '一站式AI影视制作平台，覆盖剧本创作→角色设计→分镜→AI视频生成→专业剪辑全流程，支持4K输出和Premiere Pro/DaVinci集成，Product Hunt 7月月榜上榜。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.3,
    url: 'https://ciaro.pro',
    price: '免费 / Indie $19/月 / Pro $49/月',
    features: ['剧本→成片全流程', '角色一致性', '4K视频输出', 'Premiere/Resolve集成'],
  },
  {
    id: 'stanley-studio',
    name: 'Stanley Studio',
    description: 'AI视频编辑器，上传原始素材后用自然语言描述想要的剪辑效果，AI自动完成裁剪、字幕、BGM和特效，像雇了一个真人剪辑师，Product Hunt 7月7日日榜第8名。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.2,
    url: 'https://studio.getstanley.ai',
    price: '免费',
    features: ['自然语言剪辑', '自动字幕+特效', '智能BGM匹配', '多种视频格式'],
  },
  {
    id: 'glideo',
    name: 'Glideo',
    description: 'macOS免费录屏工具，自动根据点击轨迹运镜缩放、平滑光标，零手动剪辑产出演示视频。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.1,
    url: 'https://glideo.app',
    price: '免费（个人）/ 企业合同',
    features: ['自动运镜缩放', '光标平滑', '4K导出', '完全本地私密'],
  },
  {
    id: 'focusee',
    name: 'FocuSee 2.0',
    description: 'iMobie推出的自动剪辑录屏工具，录制屏幕后AI自动生成精修演示/教程视频，含AI字幕、背景移除、语音增强、数字人和智能运镜。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.0,
    url: 'https://focusee.imobie.com',
    price: '免费试用 / 买断制（含60天退款）',
    features: ['AI自动剪辑', 'AI字幕生成', '语音增强降噪', '数字人讲解'],
  },
  {
    id: 'chatcut',
    name: 'ChatCut',
    description: '对话式AI视频编辑器，用提示词自动剪辑口播素材，智能删除填充词、提取高光、生成动态图形与字幕，浏览器即用。',
    category: 'AI视频创作',
    subCategory: 'AI视频生成',
    rating: 4.2,
    url: 'https://chatcut.io',
    price: '免费 / Plus $25/月',
    features: ['对话式剪辑', '智能去填充词', 'AI动态图形', '100+语言字幕'],
  },

  // ========================
  // 六、AI办公效率
  // ========================
  {
    id: 'gamma',
    name: 'Gamma',
    description: 'AI驱动的PPT/文档/网页生成工具，输入主题即可自动生成精美演示文稿，告别排版烦恼。',
    category: 'AI办公效率',
    subCategory: 'AI生成PPT',
    rating: 4.5,
    url: 'https://gamma.app',
    price: '免费 / Pro $10/月',
    features: ['AI生成PPT', '精美模板', '一键排版', '团队协作'],
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    description: 'AI会议助理，自动记录、转录和总结会议内容，支持实时字幕和关键词提取。',
    category: 'AI办公效率',
    subCategory: '会议助手',
    rating: 4.3,
    url: 'https://otter.ai',
    price: '免费 / Pro $16.99/月',
    features: ['会议转录', '智能总结', '实时字幕', '关键词提取'],
  },
  {
    id: 'xunfei-zhiwen',
    name: '讯飞智文',
    description: '科大讯飞推出的AI文档生成工具，支持一键生成PPT、Word文档，特别适合中文办公场景。',
    category: 'AI办公效率',
    subCategory: 'AI生成PPT',
    rating: 4.2,
    url: 'https://zw.xfyun.cn',
    price: '免费 / Pro ¥99/月',
    features: ['AI生成PPT', '中文优化', '语音输入', '模板丰富'],
  },
  {
    id: 'chatppt',
    name: 'ChatPPT',
    description: '必优科技推出的AI PPT生成工具，一句话即可生成完整PPT，支持智能排版和大纲生成，国内AI PPT赛道领跑者。',
    category: 'AI办公效率',
    subCategory: 'AI生成PPT',
    rating: 4.3,
    url: 'https://www.chatppt.cn',
    price: '免费 / 年费VIP ¥199/年 / 四年SVIP ¥398（4年，买2送2）',
    features: ['多模态生成(主题/文档/网页/图片/大纲/演讲稿)', '单页与局部AI美化', '全流程闭环(演讲稿+动画+AI路演成片+音色克隆)', '自研图笏模型中文适配', '40万+模板', '五端同步'],
  },
  {
    id: 'bond',
    name: 'Bond',
    description: 'Y Combinator孵化的AI幕僚长，自动聚合Slack/邮件/日历中的任务并按优先级排序，帮高管聚焦最高价值工作。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.3,
    url: 'https://www.bondapp.io',
    price: '$99/月/席位（年付）',
    features: ['任务智能排序', '多工具聚合', 'Slack集成', 'MCP协议'],
  },
  {
    id: 'mina',
    name: 'Mina Meeting Assistant',
    description: '主动式AI会议助手，实时参与Zoom/Teams/Google Meet会议，自动记录、回答提问并推动执行，超越被动转录。',
    category: 'AI办公效率',
    subCategory: '会议助手',
    rating: 4.2,
    url: 'https://getmina.ai',
    price: '免费试用 / 付费方案联系官方',
    features: ['实时参与会议', '自动记录笔记', '智能问答', '40+技能集成'],
  },
  {
    id: 'goldfish',
    name: 'Goldfish',
    description: 'Mac本地AI记忆助手，一键用你的语气回复所有消息，按Option即可在任何输入位置调用，Y Combinator等知名企业用户背书。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.3,
    url: 'https://goldfish.sh',
    price: 'Alpha阶段免费',
    features: ['语气模仿', '上下文感知', '全局快捷键', '本地运行'],
  },
  {
    id: 'honen',
    name: 'Honen',
    description: 'AI课程自动生成平台，将文档/录音/主题转化为交互式课程，内置AI导师，与NVIDIA合作开展25万高中生AI教育计划。',
    category: 'AI办公效率',
    subCategory: 'AI教育培训',
    rating: 4.2,
    url: 'https://honen.com',
    price: '免费 / 付费方案联系官方',
    features: ['AI课程生成', '交互式学习', 'AI导师', '自适应学习'],
  },
  {
    id: 'slashy',
    name: 'Slashy',
    description: 'Y Combinator孵化的AI邮件客户端，被称为"邮件界的Cursor"，自动起草回复、分类收件箱、追踪跟进，周均节省10+小时。',
    category: 'AI办公效率',
    subCategory: 'AI邮件助手',
    rating: 4.3,
    url: 'https://www.slashy.com',
    price: '候补名单 / 定价待公布',
    features: ['AI起草回复', '收件箱分类', '跟进追踪', '会议准备'],
  },
  {
    id: 'asmi-ai',
    name: 'Asmi AI',
    description: 'AI个人语音助理，通过真实电话帮用户处理日常事务——预约医生、比价维修、账单协商、问候家人，支持50+语言，无需下载APP。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.3,
    url: 'https://www.asmiai.com',
    price: '免费 / 付费方案联系官方',
    features: ['AI语音电话', '日常事务处理', '50+语言', '无需APP'],
  },
  {
    id: 'upstream',
    name: 'Upstream',
    description: 'YC孵化的AI原生邮件客户端，AI自动分类邮件、起草回复和智能跟进，让收件箱变轻，Product Hunt日榜第1名，获$300万融资。',
    category: 'AI办公效率',
    subCategory: 'AI邮件助手',
    rating: 4.3,
    url: 'https://upstream.do',
    price: '免费 / 付费方案联系官方',
    features: ['AI邮件分类', 'AI起草回复', '智能跟进', '语气学习'],
  },
  {
    id: 'makersclaw',
    name: 'MakersClaw',
    description: 'AI员工部署平台，一键部署专业AI Agent到Slack/Telegram/Teams，预配置客服/销售/SEO等角色，24/7运行，Product Hunt日榜第3名。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.2,
    url: 'https://makersclaw.com',
    price: '免费 / 按工具调用付费',
    features: ['AI员工部署', '多渠道集成', '持久记忆', '预配置角色'],
  },
  {
    id: 'viktor',
    name: 'Viktor',
    description: 'AI虚拟员工平台，像招人一样在Slack/Teams中添加Viktor，自动完成报告、数据分析、跨工具任务，3200+集成，获Accel领投$7500万A轮融资，服务30000+团队。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.4,
    url: 'https://viktor.com',
    price: '免费试用 / $50/月起',
    features: ['AI虚拟员工', 'Slack/Teams集成', '3200+工具连接', '自动任务调度'],
  },
  {
    id: 'invoko',
    name: 'Invoko',
    description: 'Mac端AI桌面语音助手，按Fn键即可语音操控，理解屏幕上下文，支持跨应用任务处理，所有数据本地运行保护隐私，Product Hunt日榜第2名。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.2,
    url: 'https://invoko.ai',
    price: 'Beta免费',
    features: ['语音操控', '屏幕上下文感知', '跨应用任务', '本地隐私保护'],
  },
  {
    id: 'maxeo',
    name: 'Maxeo AI',
    description: 'AI搜索品牌可见性监控平台，追踪品牌在ChatGPT、Perplexity、Claude等AI助手中的出现频率、情感倾向和竞品对比，GEO（生成式引擎优化）利器。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.0,
    url: 'https://maxeo.ai',
    price: '免费试用 / 付费方案联系官方',
    features: ['AI品牌可见性', '竞品分析', '情感监测', '内容优化建议'],
  },
  {
    id: 'fundraisly',
    name: 'Fundraisly',
    description: 'AI融资助手，分析30万+投资人数据库，自动匹配相关投资方并通过温暖介绍路径预约会议，已助200+创业公司融资超$1.7亿，Product Hunt日榜第1名。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.3,
    url: 'https://fundraisly.com',
    price: '付费方案联系官方',
    features: ['AI投资人匹配', '自动预约会议', '30万+数据库', '温暖介绍路径'],
  },
  {
    id: 'minimi',
    name: 'Minimi',
    description: 'Mac端AI环境记忆工具，自动捕获文档/通话/聊天等全维度活动上下文，通过MCP协议为Claude提供实时记忆，50%更准确的上下文理解，无需手动描述工作内容。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.3,
    url: 'https://www.projectminimi.com',
    price: 'Beta免费',
    features: ['环境记忆', 'Claude MCP集成', '本地隐私保护', '全维度上下文采集'],
  },
  {
    id: 'readywhen',
    name: 'readywhen',
    description: '24/7 AI幕僚长，自动从Slack/邮件/会议/文档中捕获所有承诺和决策，在用户开口前主动起草回复、摘要和跟进，Product Hunt日榜第5名。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.2,
    url: 'https://readywhen.ai',
    price: '创始人和管理者免费',
    features: ['承诺自动捕获', '主动起草跟进', '知识图谱', 'Slack/邮件集成'],
  },
  {
    id: 'bluerails-discovery',
    name: 'Bluerails Discovery',
    description: 'AI Agent经济支付基础设施，帮助企业被AI Agent发现并完成交易，免费分析品牌在Claude/ChatGPT中的可见性得分，Product Hunt月榜第4名。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://discovery.bluerails.com',
    price: '免费',
    features: ['AI Agent可见性分析', '多引擎查询', '品牌得分追踪', 'PDF报告导出'],
  },
  {
    id: 'elvin',
    name: 'Elvin',
    description: '主动式AI工作助手，自动监测邮箱/日历/消息，在用户开口前发现待办并起草回复，支持80+工具集成，CASA Tier 2安全认证，Product Hunt日榜上榜。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.3,
    url: 'https://tryelvin.com',
    price: 'Beta免费',
    features: ['主动式任务发现', '自动起草回复', '80+工具集成', '技能库系统'],
  },
  {
    id: 'notra',
    name: 'Notra',
    description: '开发到营销AI内容生成平台，自动将GitHub/Linear/Slack中的PR和工作转化为更新日志、发布公告和社媒内容，支持品牌语调学习。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://www.usenotra.com',
    price: '3天免费 / Pro $50/月',
    features: ['PR转营销内容', '品牌语调学习', 'GitHub/Linear集成', '社媒自动发布'],
  },
  {
    id: 'propane',
    name: 'Propane',
    description: 'AI产品管理系统，自动聚合40+工具的客户数据为一层共享智能上下文，让产品团队和AI Agent基于同一事实源构建产品，SOC 2安全认证。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://www.usepropane.ai',
    price: '免费 / 统一月费（不限用户数）',
    features: ['客户上下文聚合', '40+工具集成', 'Agent工作交接', 'SOC 2 Type II认证'],
  },
  {
    id: 'crewdle',
    name: 'Crewdle AI',
    description: '小企业一体化AI平台，集成GPT/Claude/Gemini/Grok多模型对话、AI客服Agent、内容创作、无代码建站和工作流自动化六大应用，按量付费无月费。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.3,
    url: 'https://crewdle.com',
    price: '按量付费 / 新用户免费额度',
    features: ['多模型聚合', 'AI客服Agent', '无代码建站', '工作流自动化'],
  },
  {
    id: 'zaro',
    name: 'Zaro',
    description: 'AI原生企业工作空间，统一连接数据/Agent/应用三层共享上下文，从自有文档一键生成自定义仪表盘和工具，获Cherry Ventures领投$510万，Product Hunt日榜第3名。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.3,
    url: 'https://zaro.ai',
    price: '免费 / 5000免费积分',
    features: ['上下文共享层', 'Agent工作空间', '文档生成应用', '多模型智能路由'],
  },
  {
    id: 'elentaria',
    name: 'Elentaria',
    description: 'AI驱动的B2B GTM运营系统，自动分析22个营销渠道匹配度，制定全渠道计划并自动化执行，配备资深GTM专家审核，Product Hunt月榜第8名。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://elentaria.ai',
    price: '预约演示 / 定价联系官方',
    features: ['22渠道GTM分析', '自动化执行', '人类专家审核', '全渠道绩效监控'],
  },
  {
    id: 'cotypist',
    name: 'Cotypist',
    description: 'Mac端AI智能输入补全工具，本地运行保护隐私，学习个人写作风格后在任意App中预测下一个词句，减少50%键盘输入，Apple Silicon原生支持。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.1,
    url: 'https://cotypist.app',
    price: '免费 / Pro $8/月',
    features: ['本地AI补全', '个人风格学习', '全App支持', 'Apple Silicon原生'],
  },
  {
    id: 'intelli',
    name: 'Intelli',
    description: 'AI原生B2C客户互动平台，统一WhatsApp/Web/FB/IG/Mail多渠道收件箱，AI销售助手自动跟进线索和客服，可视化对话流构建+低代码WhatsApp API集成。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.2,
    url: 'https://www.intelliconcierge.com',
    price: '免费试用 / $15/月起',
    features: ['多渠道统一收件箱', 'AI WhatsApp助手', '可视化流程构建', '营销广播+分析'],
  },
  {
    id: 'spira-ai',
    name: 'Spira AI',
    description: 'AI社交媒体内容引擎，部署自主AI网红全天候运营品牌社媒，自动挖掘热点、创作发布和学习优化，支持TikTok/Instagram/X/LinkedIn跨平台，适合创业者和团队零人工运营增长。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://spira.ai',
    price: '免费 / Creator $12/月',
    features: ['AI网红Agent', '全自动内容创作', '跨平台发布调度', '趋势监测与学习'],
  },
  {
    id: 'pluno',
    name: 'Pluno',
    description: 'AI B2B客服Agent，学习历史工单自主解决复杂技术问题，非简单FAQ匹配，月处理50万+工单、67%自动解决率，Zendesk深度集成+Jira/Slack联动，SOC-2认证。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.3,
    url: 'https://pluno.ai',
    price: '免费模拟 / 付费联系官方',
    features: ['复杂工单自动解决', '历史工单学习', 'Zendesk深度集成', 'SOC-2/GDPR合规'],
  },
  {
    id: 'lightfield',
    name: 'Lightfield',
    description: 'AI原生CRM，自动捕获邮件/会议/通话交互并构建完整客户画像，支持自然语言一句话构建Agent完成线索挖掘、跟进提醒和成交辅导，MCP/API开放平台。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://lightfield.app',
    price: '免费试用 / 付费联系官方',
    features: ['客户交互自动捕获', 'AI Agent构建', '自然语言查询', 'SOC 2/HIPAA认证'],
  },
  {
    id: 'supafax',
    name: 'Supafax',
    description: 'YC孵化的AI邮件助手，直连Gmail/Outlook，用自然语言设置规则自动处理邮件、起草回复和安排会议，14天免费试用，Product Hunt日榜第5名。',
    category: 'AI办公效率',
    subCategory: 'AI邮件助手',
    rating: 4.2,
    url: 'https://www.supafax.com',
    price: '14天免费试用 / Pro $35/月（原价$50）',
    features: ['AI邮件起草', '智能收件分类', '自然语言规则', '自动会议安排'],
  },
  {
    id: 'akiflow',
    name: 'Akiflow',
    description: 'YC S20孵化的键盘流时间块日历管理器。Universal Inbox聚合10+原生双向同步来源，Cmd+K全键盘操作，2026年6月上线托管MCP服务器mcp.akiflow.com（OAuth授权后Claude/ChatGPT可直接管任务与日历）。无免费版、计费口碑争议大、移动端与Apple日历支持弱。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 3.7,
    url: 'https://akiflow.com',
    price: '无免费版 / 7天试用（预约1:1可延至14天）/ Pro月付$34·年付$19/月($228/年) / Believer $14.90/月(两年付) / 会议助手加购+$19/月',
    features: ['托管MCP服务器mcp.akiflow.com', 'Universal Inbox聚合10+原生双向同步', 'Cmd+K键盘流时间块', 'Aki AI助手(三段简报/语音/AI Workflows)', 'Schedule Optimizer一键重排', '原生子任务Subtasks', 'Daily Dashboard日视图', '无公开REST API', '不支持Apple日历/iCloud/CalDAV'],
  },
  {
    id: 'clade',
    name: 'Clade',
    description: 'AI COO智能运营助手，直连Slack/Telegram/iMessage，用自然语言设置自动化工作流，主动追踪进度、预警风险。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.0,
    url: 'https://clade.sh',
    price: 'Beta免费 / 付费方案联系官方',
    features: ['AI COO角色', '多平台消息集成', '自然语言自动化', '项目风险预警'],
  },
  {
    id: 'macuse',
    name: 'Macuse',
    description: 'macOS原生MCP工具，让Claude/Cursor等AI直接操控日历/邮件/备忘录等系统应用，支持任意App的Computer Use自动化，数据纯本地运行，一次性买断制。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.1,
    url: 'https://macuse.app',
    price: '免费 / 终身买断制',
    features: ['MCP协议集成', '系统应用操控', 'Computer Use', '本地隐私保护'],
  },
  {
    id: 'acti',
    name: 'Acti',
    description: '全球首款Agentic键盘，将手机键盘变为AI命令层，在任何文本框长按即可调用AI执行搜索、创建、分享等任务，入选Google AI Startups，TechCrunch/Digital Trends报道。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.3,
    url: 'https://www.openacti.com',
    price: '免费',
    features: ['AI手机键盘', '任意文本域调用', 'Agent命令层', 'iOS+Android'],
  },
  {
    id: 'macro',
    name: 'Macro',
    description: '开源AI一体化工作空间，将邮件、聊天、文档、任务、通话和CRM统一到一个App，AI Agent共享记忆自动处理工作，Product Hunt日榜第6名。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.3,
    url: 'https://macro.com',
    price: '免费（个人） / Team $40/座/月',
    features: ['邮件+聊天+文档一体', 'AI Agent共享记忆', '开源GitHub', '统一工作空间'],
  },
  {
    id: 'pixfit',
    name: 'PixFit',
    description: 'AI广告素材自适应平台，上传一张主视觉即可自动生成全平台适配格式，品牌规则自动检测，Human-in-the-loop保证交付质量，Product Hunt日榜第4名。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://pixfit.ai',
    price: '免费试用 / Core $49/月',
    features: ['广告格式AI自适应', '品牌规则自动执行', '人机协同交付', '批量处理'],
  },
  {
    id: 'vida',
    name: 'Vida',
    description: '主动式AI个人克隆助手，自动学习工作习惯和偏好，在日常工作流中预判需求并起草回复、优化提示词、整理工作空间，Product Hunt 7月日榜第1名（250票），已征服5个SOTA用例。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.3,
    url: 'https://vida.app',
    price: '免费',
    features: ['AI主动预判', '跨应用上下文', '100 SOTA用例', 'Proactive Agent'],
  },
  {
    id: 'n71',
    name: 'N71',
    description: '企业AI Agent统一上下文平台，连接所有工具构建共享知识图谱，主动发现自动化机会并编排Agent执行，MEME记忆基准评测得分0.574行业最高，Product Hunt 7月日榜第15名（94票）。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.2,
    url: 'https://n71.ai',
    price: '免费试用 / 付费联系官方',
    features: ['Agent共享上下文', '知识图谱', '主动自动化', 'MEME基准领先'],
  },
  {
    id: 'mentiondrop',
    name: 'MentionDrop',
    description: '品牌监测MCP工具，连接Claude/Cursor等AI Agent实时追踪品牌提及、竞品动态和客户反馈，AI分析情感并建议回复/跟进/忽略，Product Hunt 7月6日日榜第1名。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://www.mentiondrop.com',
    price: '免费试用 / 付费方案联系官方',
    features: ['品牌监测', 'MCP Agent集成', '情感分析', '竞品追踪'],
  },
  {
    id: 'docsalot',
    name: 'DocsAlot',
    description: '面向人类和AI Agent双端的文档管理平台，将散落的产品知识转化为llms.txt/skill.md/MCP就绪文档，内置AI可见性审计确保Agent正确引用，Product Hunt 7月6日日榜第2名。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.1,
    url: 'https://docsalot.dev',
    price: 'Startup $39/月 / Team $99/月',
    features: ['AI可读文档', 'llms.txt/skill.md', 'MCP集成', 'AI可见性审计'],
  },
  {
    id: 'airkaren',
    name: 'AirKaren',
    description: 'AI消费者维权助手，输入航班延误/行李丢失等问题后自动引用法规、填写申诉、持续跟进直到获得赔偿，Harvard/Northwestern学生团队打造，Beta期完全免费，Product Hunt 7月7日日榜第7名。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.1,
    url: 'https://airkaren.com',
    price: 'Beta免费 / 后续按成功收费',
    features: ['AI自动维权', '法规引用', '持续跟进', '补偿追索'],
  },
  {
    id: 'katalyst',
    name: 'Katalyst',
    description: 'AI销售Agent，自动分析Salesforce管道中的通话/邮件/日历，实时更新客户字段，推送交易信号并生成客户计划和跟进草稿，SOC 2/ISO 27001合规，Stripe/Atlassian/Datadog等知名企业用户。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.2,
    url: 'https://www.joinkatalyst.com',
    price: '免费试用 / 付费联系官方',
    features: ['Salesforce自动更新', '通话+邮件AI分析', '交易信号推送', '客户计划自动生成'],
  },
  {
    id: 'ogment-ai',
    name: 'Ogment AI (@O)',
    description: 'Slack原生AI同事，一键安装后5分钟全员启用，1000+工具连接支持多模型（含本地LLM），团队共享记忆跨知识库学习，SOC 2合规，$100新用户免费额度。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.2,
    url: 'https://www.ogment.ai',
    price: '$50/月起 / $100免费额度',
    features: ['Slack原生Agent', '1000+工具集成', '多模型自由切换', '团队共享记忆'],
  },
  {
    id: 'ellis',
    name: 'Ellis',
    description: 'AI面对面会议笔记工具，iPhone/Apple Watch一键录音后AI自动转录并做说话人分离，支持自然语言查询对话内容，专为线下会议场景优化，区别于Otter等虚拟会议转录工具。',
    category: 'AI办公效率',
    subCategory: '会议助手',
    rating: 4.1,
    url: 'https://www.ellis.coach',
    price: '免费下载 / App内付费',
    features: ['面对面会议转录', 'AI说话人分离', '自然语言查询', 'Apple Watch支持'],
  },
  {
    id: 'lemonlime',
    name: 'LemonLime',
    description: '一句话自动化工作流的AI平台，连接现有工具构建知识图谱并自创专属部门Agent。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.0,
    url: 'https://lemonlime.ai',
    price: 'Pro $29/月（无免费档）',
    features: ['一句话自动化', '知识图谱', '自创部门Agent', '多工具集成'],
  },
  {
    id: 'toyo',
    name: 'Toyo',
    description: '活在iMessage/Telegram里的AI行政助理，自动分类邮件、起草回复、安排会议、电话跟进，连接Gmail/Calendar/Slack等工具全天候主动工作。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.0,
    url: 'https://toyo.ai',
    price: 'EA $29/月 / 团队方案联系官方',
    features: ['iMessage原生', '邮件自动分类', 'AI电话跟进', '会议准备与提醒'],
  },
  {
    id: 'kollab',
    name: 'Kollab',
    description: 'AI原生团队协作工作空间，让团队与Agents在同一空间捕捉灵感、整理素材、多格式创作并发布到社媒，支持私有化部署。',
    category: 'AI办公效率',
    subCategory: 'AI团队协作',
    rating: 4.0,
    url: 'https://kollab.im',
    price: '免费 / Pro $20/月',
    features: ['团队+Agent协作', '多格式内容创作', '素材知识库', '社媒一键发布'],
  },
  {
    id: 'wellows',
    name: 'Wellows',
    description: 'AI品牌可见性平台，追踪品牌在ChatGPT、Gemini、Perplexity等答案引擎中的引用与排名，提供内容优化与外联工具提升AI搜索曝光。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.0,
    url: 'https://wellows.com',
    price: '7天免费试用 / $37/域名/月起',
    features: ['AI可见性追踪', '竞品提示词监控', 'AI内容优化', '外联机会发现'],
  },
  {
    id: 'typewise',
    name: 'Typewise',
    description: '企业级AI客服Agent平台，用自然语言构建跨CRM/ERP的客服自动化，15分钟上线、人机协同可控、按结果付费，服务IVECO/DPD等企业。',
    category: 'AI办公效率',
    subCategory: 'AI客服助手',
    rating: 4.2,
    url: 'https://www.typewise.app',
    price: '按结果付费 / $1/次解决起',
    features: ['多Agent编排', '跨系统读写', '人机协同审批', '200+集成/MCP'],
  },
  {
    id: 'scarlett',
    name: 'Scarlett.',
    description: '活在Slack和iMessage里的AI同事，连接3000+工具自动起草PPT、写代码、建仪表盘并定时推送业务简报，Powered by Claude。',
    category: 'AI办公效率',
    subCategory: 'AI行政助手',
    rating: 4.2,
    url: 'https://tryscarlett.ai',
    price: '$50免费额度 / $29/月起',
    features: ['Slack/iMessage原生', '3000+工具集成', '端到端工作流', '定时业务简报'],
  },
  {
    id: 'connectmachine',
    name: 'ConnectMachine 2.0',
    description: '隐私优先的AI联系人管理与数字名片工具，扫描名片、记录对话，AI管家用自然语言回忆"在某某会议见过谁、为何重要"，支持CRM同步。',
    category: 'AI办公效率',
    subCategory: 'AI效率工具',
    rating: 4.1,
    url: 'https://connectmachine.ai',
    price: '免费 / Individual $5.99/月',
    features: ['AI数字名片', '名片OCR扫描', 'AI关系回忆', 'CRM同步'],
  },
  {
    id: 'bono-ai',
    name: 'Bono AI',
    description: 'AI内容策略师，通过10分钟语音访谈提取你的观点与语气，自动生成博客、社交媒体帖文和新闻通讯并多平台分发。',
    category: 'AI办公效率',
    subCategory: 'AI营销工具',
    rating: 4.0,
    url: 'https://heybono.ai',
    price: '免费 / $29/月起',
    features: ['语音访谈式创作', '多平台分发', '品牌语调学习', '博客+社媒+简报'],
  },
  {
    id: 'respan',
    name: 'Respan',
    description: 'LLM工程平台，统一API网关+可观测性+评估，支持500+模型路由、故障转移和语义缓存，处理超80万亿Token，获$500万种子轮融资。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.4,
    url: 'https://www.respan.ai',
    price: '免费 / 按量付费',
    features: ['AI网关', 'LLM可观测性', '自动评估', '500+模型'],
  },
  {
    id: 'spotlight-backplanes',
    name: 'Spotlight by Backplanes',
    description: 'AI Agent会话监控工具，自动捕获Claude Code/Codex会话，生成安全审计和工程复盘报告，由Google/Twilio前员工打造，个人和团队免费。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://www.backplanes.com',
    price: '免费（个人/团队）',
    features: ['会话监控', '安全审计', '工程复盘', 'Claude Code集成'],
  },
  {
    id: 'zerogpu',
    name: 'ZeroGPU',
    description: 'AI推理计算效率层，用专用小模型+全球边缘网络处理高流量结构化任务，降本50%+提速10倍，OpenAI兼容API即插即用。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.2,
    url: 'https://zerogpu.ai',
    price: '免费 / 按量付费',
    features: ['推理降本50%+', '边缘推理网络', 'OpenAI兼容', '专用小模型'],
  },
  {
    id: 'context-dev',
    name: 'Context.dev',
    description: '面向AI Agent的网页抓取与数据提取API，一键将任意URL转为LLM就绪的Markdown/结构化数据，支持品牌识别和网站截图，Y Combinator投资，Product Hunt月榜第1名。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.3,
    url: 'https://www.context.dev',
    price: '免费 / 按量付费',
    features: ['网页抓取API', '品牌数据提取', '结构化数据导出', 'AI Agent集成'],
  },
  {
    id: 'taste',
    name: 'Taste',
    description: 'AI设计品味提取工具，将任意网页的设计语言（配色/间距/字体/圆角/氛围）转为品味配置文件，通过MCP和SKILL.md自动同步到Cursor、Claude Code、Codex等AI编码工具。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://buildwithtaste.com',
    price: '免费 / Pro付费',
    features: ['设计DNA提取', 'MCP服务器', 'Cursor/Claude集成', '设计品味租赁'],
  },
  {
    id: 'novu-connect',
    name: 'Novu Connect',
    description: '开源AI Agent通信基础设施，一键将AI Agent部署到Slack/Teams/WhatsApp/Telegram/邮件等渠道，处理消息路由、身份解析和渠道格式化，Product Hunt日榜第1名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://novu.co',
    price: '免费开源 / 企业付费',
    features: ['多渠Agent部署', '双向通信', '开源免费', 'Claude Agent支持'],
  },
  {
    id: 'skybridge',
    name: 'Skybridge',
    description: '全栈开源React框架，一次编写即可在Claude/ChatGPT/VS Code中运行MCP App，内置HMR开发工具和本地模拟器，100K+月下载量，Datadog等企业用户，Product Hunt日榜第2名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://www.skybridge.tech',
    price: '免费开源 / Alpic云付费',
    features: ['MCP App框架', '跨客户端兼容', '热模块重载', 'Agent友好开发'],
  },
  {
    id: 'agentx',
    name: 'AgentX',
    description: 'AI Agent构建评估部署一体化平台，可视化多Agent工作流+内置测试评估+CI/CD，支持API/Slack/Web等多渠道一键部署，Product Hunt日榜第1名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://www.agentx.so',
    price: '免费 / Solo $49/月',
    features: ['Agent可视化构建', '内置评估测试', '一键多渠道部署', '白标方案'],
  },
  {
    id: 'stride',
    name: 'Stride',
    description: 'AI原生软件交付工作空间，覆盖计划→设计→验证→发布全流程，AI生成用户故事/架构方案/测试用例，支持Claude Code/Codex MCP集成，Product Hunt周榜上榜。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://www.stride.page',
    price: 'Starter $9/月 / Pro $29/座/月',
    features: ['AI用户故事生成', '架构方案设计', '测试用例生成', '全流程可追溯'],
  },
  {
    id: 'kepler',
    name: 'Kepler',
    description: 'GitKraken推出的AI智能体开发环境(ADE)，统一管理多个AI编程Agent并行工作，覆盖规划→编码→审查全流程，支持Claude Code/Codex/Open Code。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://www.gitkraken.com/kepler',
    price: '预览期免费 / Pro $5/月',
    features: ['多Agent编排', 'Kanban视图', '跨仓库并行任务', 'Agent实时纠偏'],
  },
  {
    id: 'browseract',
    name: 'BrowserAct',
    description: 'AI Agent浏览器自动化工具，隐身指纹+TLS轮转+验证码自动处理三层反检测，支持Claude Code/Cursor直接操控Chrome，20并发零干扰。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://www.browseract.com',
    price: '免费试用 / AppSumo买断$49起',
    features: ['隐身浏览器', '验证码自动处理', 'Chrome登录态复用', 'Agent友好输出'],
  },
  {
    id: 'oxlo-ai',
    name: 'Oxlo.ai',
    description: '隐私优先AI推理API平台，支持Kimi K2.6等45+模型，按次定价非Token计费，零数据留存，Product Hunt日榜第1名。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.3,
    url: 'https://www.oxlo.ai',
    price: '免费 / Pro $80/月（按次定价）',
    features: ['45+模型接入', '按次定价', '隐私零留存', 'Agent工具调用'],
  },
  {
    id: 'qapilot-cowork',
    name: 'QApilot CoWork',
    description: 'AI辅助移动测试自动化平台，将Jira/TestRail/CSV中现有测试用例转为可执行自动化，人机协同重规划、真实设备执行，支持iOS/Android/Flutter，Product Hunt日榜第2名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://qapilot.io/product/cowork',
    price: '免费规划 / 付费方案联系官方',
    features: ['测试用例自动激活', '人机协同重规划', '真实设备执行', '跨平台测试'],
  },
  {
    id: 'modelence',
    name: 'Modelence',
    description: 'YC投资的AI全栈应用构建器，自然语言描述即可生成含认证/数据库/监控的生产级Web+移动App，开放源码无供应商锁定，本周新增原生移动端构建支持。',
    category: 'AI编程开发',
    subCategory: '云端开发',
    rating: 4.2,
    url: 'https://modelence.com',
    price: '免费 / 付费方案联系官方',
    features: ['全栈应用生成', '移动端构建', '一键生产部署', 'YC投资开源框架'],
  },
  {
    id: 'glaze',
    name: 'Glaze by Raycast',
    description: 'Raycast推出的AI桌面应用构建工具，通过自然语言对话即可生成原生Mac应用，本地运行、离线可用、OS深度集成，Product Hunt日榜第1名（535票）。',
    category: 'AI编程开发',
    subCategory: '云端开发',
    rating: 4.4,
    url: 'https://www.glaze.app',
    price: '免费 / Pro付费',
    features: ['AI对话建应用', '原生Mac体验', '本地离线运行', '应用商店分发'],
  },
  {
    id: 'clusy',
    name: 'Clusy',
    description: 'Agent原生ML/数据科学笔记本平台，用自然语言描述需求即可在云端CPU/GPU上端到端执行数据分析和模型训练，支持分支实验对比，Product Hunt日榜上榜。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://www.clusy.io',
    price: '免费 / Plus $30/月 / Pro $90/月',
    features: ['Agent原生笔记本', '端到端ML工作流', '云端GPU执行', '分支实验对比'],
  },
  {
    id: 'humalike',
    name: 'Humalike',
    description: 'AI Agent行为基础设施平台，提供7种行为API（轮流发言/社交规范/心理理论/社交记忆等），让AI Agent拥有人类般的社交智能，Product Hunt日榜第2名（454票）。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://humalike.ai',
    price: '即将公布定价',
    features: ['社交行为API', '轮流发言引擎', '心理理论追踪', '多场景Agent适配'],
  },
  {
    id: 'tabstack',
    name: 'Tabstack',
    description: 'Mozilla推出的AI Agent网络执行层API，一次调用实现结构化数据提取、网页研究和浏览器自动化，免浏览器和LLM编排，10000免费额度，开源浏览器引擎Pilo，Product Hunt 7月月榜第6名（119票）。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.3,
    url: 'https://tabstack.ai',
    price: '免费 / Team $99/月 / Pro $499/月',
    features: ['API数据提取', '浏览器自动化', '网页研究Agent', 'Mozilla隐私标准'],
  },
  {
    id: 'scritty',
    name: 'scritty',
    description: 'AI Agent终端记忆系统，自动捕获Claude Code/Codex/Copilot等所有CLI Agent对话，建立跨供应商统一可搜索记忆库，本地加密存储，MCP协议反馈，Product Hunt日榜第9名（124票）。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.3,
    url: 'https://scritty.dev',
    price: '免费试用 / Personal $19.99/月 / Pro $249.99/月',
    features: ['Agent对话捕获', '跨供应商搜索', '本地加密存储', 'MCP记忆反馈'],
  },
  {
    id: 'trycase',
    name: 'TryCase',
    description: 'AI编程Agent一次性测试环境，为Claude/Cursor等Agent提供可销毁Linux桌面运行和测试应用，自动返回截图、录屏和日志作为验证证明，Product Hunt 7月6日日榜第6名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://www.trycase.dev',
    price: '测试期免费 / 付费方案联系官方',
    features: ['Agent测试环境', '浏览器自动化', '截图录屏验证', 'CLI+Skills集成'],
  },
  {
    id: 'anysearch',
    name: 'AnySearch',
    description: '专为AI Agent打造的搜索基础设施，提供过滤、去重和结构化搜索结果API，原生支持MCP和Skill集成，每日1000次免费调用，PR Newswire 5月专题报道。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.2,
    url: 'https://www.anysearch.com',
    price: '免费 / 按量付费',
    features: ['Agent搜索API', '结构化数据输出', 'MCP协议支持', '垂直领域搜索'],
  },
  {
    id: 'circlechat',
    name: 'CircleChat',
    description: '开源AI Agent协作工作空间，给Agent配备Slack式频道+看板+审批流程，Agent自主认领任务、互相协作并由独立审查者验证输出，MIT协议自托管免费，Product Hunt日榜第6名。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://circlechat.co',
    price: '自托管免费 / Cloud $29/月',
    features: ['Agent看板管理', '任务自动路由', '独立审查验证', '开源MIT协议'],
  },
  {
    id: 'codemote',
    name: 'CodeMote',
    description: 'iPhone遥控CLI编程Agent工具，支持Claude Code/Codex等任意终端Agent，实时终端+Diff+GIT全流程操作，端到端加密代码不上传服务器，锁屏Live Activity推送Agent等候通知。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.1,
    url: 'https://codemote.caste.work',
    price: '7天免费试用 / 付费方案',
    features: ['iPhone远程Agent', '实时Diff审查', '端到端加密', '锁屏Live Activity'],
  },
  {
    id: 'agents-cli',
    name: 'Agents CLI (Google)',
    description: 'Google开源CLI与技能包，让编码Agent在Google Cloud上构建、评估并部署AI智能体。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://google.github.io/agents-cli/',
    price: '免费开源',
    features: ['AI Agent构建', 'Google Cloud部署', '编码Agent协同', 'ADK集成评估'],
  },
  {
    id: 'magic-patterns',
    name: 'Magic Patterns Agent 2.0',
    description: '面向产品团队的AI设计Agent，从想法生成匹配设计系统的可交互UI原型，并导出生产级代码，支持Skills/Connectors/MCP 2.0，SOC 2与ISO 27001认证。',
    category: 'AI编程开发',
    subCategory: 'AI设计',
    rating: 4.0,
    url: 'https://www.magicpatterns.com',
    price: '免费 / Starter $20/座/月',
    features: ['想法转UI原型', '设计系统匹配', '生产级代码导出', 'MCP 2.0集成'],
  },
  {
    id: 'aura',
    name: 'Aura',
    description: 'Git原生AI编程IDE，将Claude Code/Cursor/Codex等Agent统一到一个语义引擎，提供AST级差异、目标↔提交证明链与可溯源审计，完全开源。',
    category: 'AI编程开发',
    subCategory: 'AI编辑器',
    rating: 4.1,
    url: 'https://auravcs.com',
    price: '免费（开源 Apache-2.0）',
    features: ['多Agent统一引擎', 'AST语义级Diff', '目标↔提交证明', '完全开源'],
  },
  {
    id: 'prometheus-firecrawl',
    name: 'Prometheus by Firecrawl',
    description: 'Firecrawl推出的"前线城市部署Agent"，用自然语言生成可验证、可自修复的TypeScript网页采集器，支持定时部署与API输出。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.3,
    url: 'https://www.firecrawl.dev/prometheus',
    price: '免费 / 按Firecrawl积分计费（$16/月起）',
    features: ['自然语言转采集器', '代码可验证自修复', '定时+API部署', 'HTTP/CLI/MCP集成'],
  },
  {
    id: 'agentkey',
    name: 'AgentKey',
    description: 'Chainbase Labs出品的Agent数据接入层，一个Key让Claude Code/Cursor等AI Agent访问搜索、社媒、链上、金融等实时数据，自动故障转移。',
    category: 'AI编程开发',
    subCategory: 'AI工具链',
    rating: 4.2,
    url: 'https://agentkey.app',
    price: '免费 / 按次计费（无月费）',
    features: ['Agent实时数据', 'MCP插件', '多源故障转移', '40+Agent客户端'],
  },
  {
    id: 'opper-ai',
    name: 'Opper AI',
    description: '欧洲（斯德哥尔摩）托管的AI网关，一个OpenAI兼容API接入300+模型，GDPR合规、自动故障转移与全量审计，专为Agent设计。',
    category: 'AI编程开发',
    subCategory: 'AI基础设施',
    rating: 4.2,
    url: 'https://opper.ai',
    price: '免费 / 按量付费（GDPR合规）',
    features: ['300+模型网关', 'EU数据驻留', '自动故障转移', '全量审计追踪'],
  },

  // ========================
  // 七、AI搜索工具
  // ========================
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI搜索引擎标杆产品，以对话形式返回搜索结果，附权威来源链接，替代传统搜索引擎的利器。',
    category: 'AI搜索工具',
    subCategory: 'AI搜索引擎',
    rating: 4.6,
    url: 'https://www.perplexity.ai',
    price: '免费 / Pro $20/月',
    features: ['对话搜索', '来源引用', '深度研究', '文件分析'],
  },
  {
    id: 'mita-ai',
    name: '秘塔AI搜索',
    description: '国产AI搜索引擎，无广告、结构化展示搜索结果，支持深度研究和学术检索，体验流畅。',
    category: 'AI搜索工具',
    subCategory: 'AI搜索引擎',
    rating: 4.5,
    url: 'https://metaso.cn',
    price: '免费',
    features: ['无广告搜索', '结构化结果', '深度研究', '学术检索'],
  },
  {
    id: 'devv',
    name: 'Devv AI',
    description: '面向开发者的AI搜索引擎，专注技术问题解答，索引GitHub、文档和Stack Overflow等优质技术源。',
    category: 'AI搜索工具',
    subCategory: '开发者搜索',
    rating: 4.3,
    url: 'https://devv.ai',
    price: '免费',
    features: ['技术搜索', 'GitHub索引', '代码示例', '文档查询'],
  },
  {
    id: 'yahoo-scout',
    name: 'Yahoo Scout',
    description: 'Yahoo推出的AI答案引擎，基于Claude模型结合30年Yahoo数据积累，提供带来源链接的结构化搜索结果，免费使用。',
    category: 'AI搜索工具',
    subCategory: 'AI搜索引擎',
    rating: 4.1,
    url: 'https://scout.yahoo.com',
    price: '完全免费（含广告，仅限美国beta）',
    features: ['Claude驱动', '9条来源链接', 'Yahoo生态', '结构化答案'],
  },
  {
    id: 'felo',
    name: 'Felo',
    description: '日本团队打造的多语言AI搜索引擎，支持学术检索、日文专长和PPT一键生成，跨语言信息检索能力突出。',
    category: 'AI搜索工具',
    subCategory: 'AI搜索引擎',
    rating: 4.2,
    url: 'https://felo.ai',
    price: '免费 / Pro $14.99/月（年付$12.5/月）',
    features: ['多语言搜索', 'PPT生成', 'Felo Agent', '日文专长'],
  },
  {
    id: 'consensus',
    name: 'Consensus',
    description: '专注科学研究的AI搜索引擎，检索2.2亿+同行评审论文，用Consensus Meter展示学界态度，杜绝AI幻觉。',
    category: 'AI搜索工具',
    subCategory: 'AI搜索引擎',
    rating: 4.3,
    url: 'https://consensus.app',
    price: '免费 / Pro $15/月 / Deep $65/月',
    features: ['论文检索', 'Consensus Meter', '引用导出', '循证决策'],
  },

  // ========================
  // 八、AI音乐音频
  // ========================
  {
    id: 'suno',
    name: 'Suno',
    description: 'AI音乐生成领域的领跑者，输入歌词和风格提示即可生成完整的歌曲，支持人声和多种音乐流派。',
    category: 'AI音乐音频',
    subCategory: 'AI音乐',
    rating: 4.5,
    url: 'https://suno.com',
    price: '免费 / Pro $10/月',
    features: ['文生音乐', '歌词生成', '多风格', '完整歌曲'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: '最逼真的AI语音合成平台，支持文本转语音、语音克隆和配音，音质达到真人级水平。',
    category: 'AI音乐音频',
    subCategory: 'AI语音',
    rating: 4.6,
    url: 'https://elevenlabs.io',
    price: '免费 / Pro $5/月',
    features: ['语音合成', '语音克隆', '情感表达', '多语言'],
  },
  {
    id: 'udio',
    name: 'Udio',
    description: 'AI音乐生成工具，支持多种风格和人声，音质出色，Suno最强竞品，适合音乐创作者和内容制作者。',
    category: 'AI音乐音频',
    subCategory: 'AI音乐',
    rating: 4.3,
    url: 'https://udio.com',
    price: '免费 / Pro $10/月',
    features: ['文生音乐', '多风格', '高质量人声', 'Stem分离'],
  },
  {
    id: 'aiva',
    name: 'AIVA',
    description: 'AI古典与电影配乐作曲工具，支持250+音乐风格、MIDI导出和DAW编辑，Pro版拥有完整版权，适合专业作曲和影视配乐。',
    category: 'AI音乐音频',
    subCategory: 'AI音乐',
    rating: 4.2,
    url: 'https://www.aiva.ai',
    price: '免费 / Pro €33/月（完整版权）',
    features: ['管弦乐配乐', '250+风格', 'MIDI导出', '完整版权'],
  },
  {
    id: 'willow-voice',
    name: 'Willow Voice',
    description: '跨Mac/Windows/iPhone的AI语音听写工具，3倍准确率、200ms低延迟、自动格式化文本。',
    category: 'AI音乐音频',
    subCategory: 'AI语音',
    rating: 4.3,
    url: 'https://willowvoice.com',
    price: '免费下载 / Pro付费',
    features: ['AI语音听写', '跨平台支持', '自动格式化', '100+语言'],
  },

  // ========================
  // 九、AI工作台（桌面智能体 / Agent 工作台）
  // ========================
  {
    id: 'autoclaw',
    name: 'AutoClaw（澳龙）',
    description: '智谱AI一键安装版OpenClaw桌面智能体，下载双击1分钟本地部署，内置Pony-Alpha-2模型与50+技能，支持AutoGLM浏览器自动化与飞书集成。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.3,
    url: 'https://autoclaws.org',
    price: '免费体验 / 积分付费',
    features: ['一键本地部署', 'Pony-Alpha-2模型', '50+预置技能', 'AutoGLM浏览器自动化'],
  },
  {
    id: 'arkclaw',
    name: 'ArkClaw',
    description: '火山引擎（字节）云端托管版OpenClaw智能体，零门槛7×24小时在线运行，深度集成飞书，搭配方舟Coding Plan低成本使用。',
    category: 'AI工作台',
    subCategory: '云端智能体',
    rating: 4.2,
    url: 'https://www.volcengine.com/product/arkclaw',
    price: '绑定方舟Coding Plan（免费试用）',
    features: ['云端免部署', '7×24在线运行', '飞书深度集成', 'Skill Hub技能市场'],
  },
  {
    id: 'kimi-work',
    name: 'Kimi Work',
    description: '月之暗面推出的桌面AI智能体，本地运行、WebBridge自主操控浏览器，自然语言驱动办公自动化与本地文件处理。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.3,
    url: 'https://kimi.com/work',
    price: '免费 / 会员增值',
    features: ['桌面智能体', 'WebBridge浏览器操控', '本地文件处理', '长文本优势'],
  },
  {
    id: 'qoderwork',
    name: 'QoderWork',
    description: 'Qoder团队（阿里系）桌面AI助手，自主规划+本地文件操作+技能市场；2026年7月已并入阿里「千问办公」统一序列。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://qoder.com/qoderwork',
    price: 'Pro $19/月（邀请制beta）',
    features: ['自主任务规划', '本地文件操作', 'Skill技能市场', 'MCP集成'],
  },
  {
    id: 'krowork',
    name: 'KroWork',
    description: '国产桌面AI智能体，对话即可生成可分享的本地Agent应用，内置20+技能、Kro Browser Bridge自主网页操控，支持飞书/Slack/Telegram远程触发。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://krowork.com',
    price: '免费 / 积分制',
    features: ['对话生成桌面应用', '20+内置技能', 'Kro Browser Bridge', '应用一键分享'],
  },
  {
    id: 'fellou',
    name: 'Fellou',
    description: '全球首款代理式AI浏览器（Agentic Browser），桌面端自动规划并执行跨网站与本地任务，内置Computer Use与Agentic Memory。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://www.fellou.ai/',
    price: '免费(1000 Sparks) / Plus $19·Pro $39.9·Ultra $199.9 月',
    features: ['Agentic浏览器', '先规划后执行', 'Computer Use本地操控', 'Agentic Memory', '跨站深研报告', '可实时介入'],
  },
  {
    id: 'rowboat',
    name: 'Rowboat',
    description: '本地优先的开源AI同事，将邮件/会议/聊天沉淀为可关联的知识图谱，自带邮件、笔记、浏览器、代码等工作台面，数据存本地Markdown。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://www.rowboatlabs.com',
    price: '完全免费开源（Apache-2.0）/ 模型与语音搜索等第三方服务成本自付',
    features: ['本地优先', '知识图谱记忆', '邮件自动起草', '本地会议记录', '后台Agent', 'Code Mode并行编码', '内置隔离浏览器', '可自建工作应用', 'MCP集成', '自带模型'],
  },
  {
    id: 'lobsterai',
    name: 'LobsterAI（有道龙虾）',
    description: '网易有道开源桌面级办公Agent，连接文件/终端/浏览器自主执行，GUI一键安装，钉钉飞书远程指挥+MCP技能商店。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.3,
    url: 'https://lobsterai.youdao.com',
    price: '免费开源（MIT）/ 自带模型或API Key',
    features: ['桌面级Agent', 'GUI一键安装', 'IM手机远程指挥', '16+内置技能', 'MCP技能商店', 'QEMU沙箱隔离', '本地SQLite数据', '13套专家套件'],
  },
  {
    id: 'chatgpt-work',
    name: 'ChatGPT Work',
    description: 'OpenAI自主Agent工作台：GPT-5.6跨文件/应用/浏览器自主推进任务数小时，交付文档、表格、幻灯片与可交互Sites。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.5,
    url: 'https://openai.com/chatgpt-work',
    price: '随ChatGPT订阅包含 / 桌面端全计划免费，Web·移动端需Plus $20/月起',
    features: ['跨应用自主Agent', '数小时连续执行', '1400+插件连接器', 'Sites实时网页产物', '定时/触发任务', 'GPT-5.6驱动'],
  },
  {
    id: 'hermes-agent',
    name: 'Hermes Agent',
    description: 'Nous Research出品的跨平台开源AI Agent运行时：长期记忆+技能自学习+MCP，v0.20支持流式语音、A2A互联与可溯源研究，覆盖飞书/钉钉/微信等20+渠道。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://hermes-agent.nousresearch.com',
    price: '开源免费（MIT）/ Nous Portal托管云 $20·100·200 月',
    features: ['长期记忆', '技能自学习', 'MCP集成', 'v0.20桌面端', '流式语音', 'A2A互联', '可溯源研究', '定时任务', '跨20+渠道'],
  },
  {
    id: 'stepclaw',
    name: 'StepClaw（阶跃龙虾）',
    description: '阶跃星辰出品的零门槛桌面AI智能体：OpenClaw深度优化成桌面宠物，水产市场捡技能、微信远程指挥，本地加密记忆。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.1,
    url: 'https://www.stepfun.com/download',
    price: '客户端免费 / Step Plan ¥49·99·199·699 月（年付低至 ¥38/月）',
    features: ['桌面宠物UI', '零命令行部署', '水产市场5000+技能', '微信/飞书远程指挥', '本地加密记忆', '定时/触发任务', '三级权限管控', '信通院安全认证'],
  },
  {
    id: 'claude-cowork',
    name: 'Claude Cowork',
    description: 'Anthropic官方桌面Agent：给定目标后跨本地文件与工具端到端执行，沙箱VM隔离、逐步可见、删除需审批，交付成品待审。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.5,
    url: 'https://claude.com/product/cowork',
    price: '随Claude付费订阅包含（Pro $17/月起，Max $100–200/月，Team $30/人/月）',
    features: ['本地文件夹端到端任务', '沙箱VM隔离', '屏幕接管操控', '定时无人值守任务', '并行子任务', '插件市场+MCP连接器', '删除需审批', 'Web/桌面/移动全端'],
  },
  {
    id: 'manus',
    name: 'Manus',
    description: '现象级自主AI Agent：给定目标即在沙箱云VM里规划-浏览-写码-出稿端到端交付，My Computer桌面版可读写本地文件与应用（Meta收购被叫停，腾讯牵头回购谈判中）。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://manus.im',
    price: '免费(每日300积分) / Pro $20-40/月 / Pro Max $200/月',
    features: ['规划-执行多Agent架构', '沙箱云VM(浏览器+终端+文件)', 'Wide Research并行子Agent', 'My Computer桌面版操本地', '应用/网站构建+Stripe', '深度网研带引用', '实时可视执行', 'GAIA基准领先'],
  },
  {
    id: 'genspark',
    name: 'Genspark',
    description: '全能型AI工作台：一句话调度70+模型+80+工具自主出稿，Claw「AI员工」独占云VM跨会话执行，还能AI打电话、原生嵌入Office。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://www.genspark.ai',
    price: '免费(100-200积分/天) / Plus $24.99月($19.99年付) / Pro $249.99月($199.99年付)',
    features: ['Super Agent一句话执行', '70+模型混合编排', 'Claw专属云VM持久记忆', 'AI打电话预订', 'Slides/Sheets/Docs生成', 'Word/Excel/PPT原生插件', '6000+企业客户', 'GAIA 87.8%(自报)'],
  },
  {
    id: 'minimax-agent',
    name: 'MiniMax Agent 2.0',
    description: 'MiniMax出品的AI原生工作台：桌面端直接操作本地文件与浏览器，Expert Agents注入私有知识库和SOP打造领域专家分身。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.4,
    url: 'https://agent.minimaxi.com',
    price: '会员订阅制，专业任务消耗积分 / Expert Agents限时免费',
    features: ['桌面端操本地文件(Win/Mac)', 'Expert Agents专家分身', '私有知识库+SOP注入', '网页自动化', '长期记忆', '子代理自定义与协作', 'MiniMax Space网页部署', 'M2.1模型驱动'],
  },
  {
    id: 'skywork-desktop',
    name: 'Skywork 桌面版',
    description: '昆仑万维出品的Windows优先桌面Agent：本地读取全盘文件跨格式理解，多模型可切换+100余项Skills，交付可编辑的PPT/表格/文档/网站。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.3,
    url: 'https://skywork.ai/desktop',
    price: '订阅制（Basic / Plus会员，Skywork 2.0取消积分制改为无限使用）',
    features: ['本地执行免上传云端', '跨格式统一语义理解(图/表/PPT/文档)', 'Claude/GPT/Gemini/DeepSeek多模型切换', '100+内置Skills自动匹配', '并行子Agent协作', '本地虚拟机隔离安全', '定时自动化任务', 'Windows 10+/macOS 12+(Apple Silicon)'],
  },
  {
    id: 'qwenpaw',
    name: 'QwenPaw（原CoPaw）',
    description: '阿里通义AgentScope团队开源的个人智能体工作站：本地部署数据不出门，钉钉/飞书/微信远程指挥，Skills自动加载扩展。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.3,
    url: 'https://qwenpaw.agentscope.io',
    price: '开源免费（Apache 2.0），模型可用本地llama.cpp/Ollama零API Key',
    features: ['本地/云端一键部署', '钉钉/飞书/微信/Discord/Telegram多渠道接入', 'Skills自动加载+定时任务', '主动心跳机制', '多Agent协作+Mission自主任务', '本地模型零API Key', '三层安全防护(工具守卫/文件访问控制/技能扫描)', '桌面App(Tauri)+pip/Docker/魔搭多安装方式'],
  },
  {
    id: 'jiuwenswarm',
    name: 'JiuwenSwarm（蜂群智能体）',
    description: '华为openJiuwen社区开源的多智能体协同工作台：自动组建Agent团队并行干活，人可入队协作（HITS），全平台含鸿蒙PC。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://www.openjiuwen.com/jiuwenswarm',
    price: '开源免费（Apache 2.0），需自配模型（支持华为云/多模型接入）',
    features: ['个人助手(Claw)/编码(Coding)/集群(Swarm)三模式', '自动组建多Agent团队并行分工', 'HOTS/HITS人机协同（人可作为蜂群成员入队）', 'Swarm Skills团队技能沉淀+Skills Hub共享', '小艺/飞书/钉钉/Telegram多频道远程指挥', '首个鸿蒙PC开源AI统一工作台（Win/Mac/HarmonyOS）', 'Skills自演进+分层记忆+上下文瘦身', 'PinchBench 94.2%业界SOTA（官方数据）'],
  },
  {
    id: 'dumate',
    name: 'DuMate（百度搭子）',
    description: '百度智能云出品的桌面级办公智能体：在本地沙箱内整理文件、跨表分析出报告、跨应用自动化，高危操作需二次授权。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.2,
    url: 'https://dumate.baidu.com',
    price: '个人免费版每日登录赠1000积分；Pro 59元/月、Max 129元/月；企业版189元/席位/月',
    features: ['本地安全沙箱隔离运行', '文件夹级权限管控+高危操作二次确认+全程可审计', '文件智能分类归档与Office/PDF批量互转', '多表关联分析并自动生成汇报PPT', '跨应用/网页自动化+操作录制回放', '定时任务调度', '技能广场+自定义技能', '内置百度搜索Skill', '飞书/微信/钉钉/如流渠道接入', 'Windows/macOS/移动端'],
  },
  {
    id: 'aipy',
    name: '爱派 AiPy',
    description: '知道创宇开源的本地AI数字员工：把自然语言现场转成Python代码并在本机执行，交付结果而非建议。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.1,
    url: 'https://www.aipyaipy.com',
    price: '开源核心免费（pip install aipyapp，Apache 系协议，需自配模型API Key）；AiPy Pro 桌面客户端免费下载、需手机/微信注册登录',
    features: ['Python-Use范式：无工具插件/无MCP，直接生成并执行代码', '任务→计划→代码→执行→反馈自动闭环，报错自修复', '本地执行，数据不出本机', '直接读写本地Excel/Word/PDF/图片等文件', '可操控浏览器、局域网设备、打印机、FreeCAD等本机软件', '开源命令行版(GitHub knownsec/aipyapp)+Pro桌面客户端双形态', '支持DeepSeek等主流模型自配API Key', 'Windows/macOS/Linux，兼容海光CPU与银河麒麟、统信UOS信创系统'],
  },
  {
    id: 'qwenwork',
    name: '千问办公（QwenWork）',
    description: '阿里出品的办公智能体，整合QoderWork/悟空/MuleRun：一句话交付Office产物与网页，可在钉钉侧边栏直接调用。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.0,
    url: 'https://qwenwork.cn',
    price: '个人免费版（注册赠2000积分，每日登录赠100积分）；个人标准版98元/月（连续包月8折78元）、高级版198元/月（8折158元）；企业标准版198元/席位/月，旗舰版需咨询',
    features: ['整合QoderWork(桌面交互)+MuleRun(流程复用)+悟空(钉钉企业数据)三层架构', '钉钉企业IM 25项能力打通：群聊/考勤审批/会议日程/知识库/邮件直读', '原生生成PPTX/Word/Excel/HTML产物并支持在线预览与实时编辑', '全栈网页生成，自带默认域名+数据库+托管，免部署发布', '多模态理解与生成：图片/音频/视频识别与素材创作', '专家套件与技能市场，覆盖HR/律师/财务/分析师等十余岗位', '桌面端支持本地文件操作、电脑操控、浏览器自动化、语音输入', '云端定时任务，结果自动推送至钉钉消息', '继承企业权限体系+安全沙箱运行+数据链路可追溯', '桌面端Windows 10+/macOS 14+/HarmonyOS 6.1+，网页端Beta，钉钉内置版'],
  },
  {
    id: 'openworker',
    name: 'OpenWorker',
    description: '吴恩达团队开源的桌面AI同事：自带模型Key，跨Slack/邮件/日历交付成品，关键操作需审批。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 3.8,
    url: 'https://openworker.com',
    price: '应用本体 MIT 开源完全免费、无订阅费（官网FAQ：直接付费给模型厂商，一分钱不付给我们）；需自备模型 API Key，或接 Ollama 跑本地模型零推理成本',
    features: ['交付成品导向：直接产出文档/表格/报告/网页文件，而非待办清单', '模型无关：基于自研 aisuite 统一接口，官方原生支持 OpenAI/Anthropic/Gemini/Inkling/GLM/DeepSeek/Kimi/Qwen/MiniMax/Mistral/Grok 十一家，另经 Together、Fireworks 接开源权重，可对话框内直接切换不重启', '本地优先：Agent 引擎、会话记录、连接器 Token、模型密钥均存本机', '支持 Ollama 本地模型，可完全离线运行', '25+ 连接器：Slack/Gmail/Outlook/Google Calendar/GitHub/Jira/Notion/Linear/HubSpot/monday.com 等', 'Slack 中 @OpenWorker 即在桌面端开启会话，完成后将结果回帖至原线程', '可读写本地文件并执行 Shell 命令，桌面即工作空间', '接入 MCP 协议，支持按工具单独授权', '定时自动化任务（晨报/周报/频道监控），运行留完整执行日志', '写入/发送/执行类操作强制审批，无人值守时挂起到收件箱待批', 'macOS 12+（仅 Apple Silicon 有签名公证包，自动更新）/Windows 10/11 x64（尚未代码签名，SmartScreen 会告警），无 Linux 版、无中文界面', 'Open Beta 阶段（最新 v0.1.7，2026-07-30）；Skills 支持于 2026-08-01 合入但官方说明当前仅为占位实现'],
  },
  {
    id: 'lingxi-pro',
    name: '灵犀专业版',
    description: '金山办公出品的AI原生桌面办公助理，基于WPS文档内核直接交付可继续编辑的Word/Excel/PPT成品。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.0,
    url: 'https://www.lingxi.cn',
    price: '2026-08-03起正式收费，按灵点计费（灵点有效期1个月、过期作废）：体验版限时免费每月800灵点；标准版48元/月5000灵点（首月加赠5000，约104灵点/元）；进阶版128元/月14000灵点（首月加赠14000，约109灵点/元）；旗舰版398元/月48000灵点（首月加赠48000，约121灵点/元）；加量包25元/2000灵点（80灵点/元、1年有效，限标准版及以上购买）。WPS大会员权益与灵点体系完全不打通',
    features: ['文档内核级处理：调用WPS文档内核、CLI与JSAPI做格式排版/表格公式/PPT动效，非接口拼凑', '产出原生可继续编辑的成品：表格保留公式与条件格式、图表用标准控件、PPT为标准母版结构可改版', 'WPS AI表格Agent于2026-07-11以98.25%登顶SpreadsheetBench的Verified 400专家精标榜第一，6月已以73.46%拿下Full 912全量榜冠军并首超人类专家基线', '四层记忆架构：个人记忆/专家记忆/团队记忆/自进化，按项目沉淀上下文与写作风格；正式发布后新增自动做梦后台记忆整理，支持从其他AI导入记忆，记忆可查看/修改/删除', '可授权接续WPS云文档中的存量历史文件，记忆起点不从零算起', '可直接操作WPS多维表格API并生成AirScript脚本（社区实测一次80-90灵点、固化后执行零消耗；10分钟批量创建103个客户视图）；但多维表API目前仅支持创建视图，筛选条件需手动补充', '内置同花顺/国家统计局/arXiv等权威数据源，供金融、法律、学术场景取数', '技能生态：内置文档/数据/演示技能，可把重复工作流封装为自定义技能', '桌面端支持定时任务、系统级操作与深度文件管理，可执行本地指令与调用浏览器；社区实测定时任务最多设置15天、最多同时运行5个', 'IM多频道接入QQ/钉钉/飞书/企业微信/金山文档，电脑不在手边可用手机远程下发任务', 'Pro/Max双模式（不同模型能力等级的开关），官方社区同任务横评Pro约10灵点、Max约167灵点，相差约16倍', '模型基座官网未公示；客户端支持添加自定义模型，但用户反馈外接模型同样消耗灵点', '桌面客户端1.2.27（Windows 10/11 + macOS Apple/Intel），Web版lingxi.kdocs.cn；Office插件、Chrome插件与微软Office版官网均标注即将上线；无独立移动App；官方答复暂不支持统信UOS', '内测期名为WPS灵犀Claw需邀请码，正式发布后已开放注册无需邀请码；注意与WPS AI（含在大会员）、WPS Comate（面向企业）区分'],
  },
  {
    id: 'agentsky',
    name: 'AgentSky',
    description: '把Claude Code、OpenClaw等Agent搬到云端托管长跑，掉线自动恢复，多个IM渠道共用同一上下文。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 3.6,
    url: 'https://agentsky.dev',
    price: '无订阅费与席位费，注册赠 $3 额度、无需信用卡。预付额度按两条计量线扣除——模型 token 按各厂商公开价计（Claude Fable 5 输入 $15 / 输出 $75 每百万 token，DeepSeek V4 Flash 低至 $0.21 / $0.42）；算力按机器唤醒秒数计，1GB $0.021/小时、2GB $0.038/小时、4GB 默认机 $0.071/小时，对应常亮月上限 $15.24 / $27.16 / $51.01，不足一分钟的碎片不计。挂起与停放的 Agent 零费用。官方估算器：Claude Fable 5 + 4GB + 每天 20 轮 + 每天唤醒 2 小时 = 月 $121.25（其中 $117 是模型、$4.25 是算力）。绑定自有 Claude Pro/Max 或 ChatGPT 订阅后，符合条件的 Agent 模型侧按 $0 计。定价页只公布到 4GB，agent.toml 允许声明的 8 vCPU 机型价格未公开',
    features: [
      'Harness 无关：hermes（默认）/ claude_code / codex / openclaw 四选一，harness 软件本身免费，事后可更换且不丢历史',
      '模型无关：Claude Fable 5/Opus 5/Sonnet 4.6、GPT-5.6 Sol/Terra/Luna、Gemini 3.5 Flash、DeepSeek V4 Pro/Flash、GLM-5.2、Kimi K3 共 11 款逐条明码标价；但兼容性非全矩阵，官网公告 Kimi K3 仅在 Hermes 与 OpenClaw 可用',
      '全渠道可达：官网列 WhatsApp / iMessage / Telegram / Slack / Web / A2A 协议 / CLI 共 7 项，共用同一 Agent 的历史、工具与状态；chatgate、aitoolly 等第三方站另称含 Discord，官网首页未列；跨渠道身份归并规则官方未公开',
      'sky clone：把本机 Claude Code 等已配好的 Agent 克隆上云，带走指令文件、模型与不含密钥的 MCP Server——但 CLI 文档明写 never secrets or history，历史一条不过去、密钥须用 sky secrets set 重设，且标注 Claude Code first',
      '持久化运行时：托管 worker 配快照、备份与故障自动恢复，官方称连续历史长度无上限；但 maker 在 Product Hunt 讨论区承认状态恢复是 best-effort、无法排除竞态，快照不可当作外部副作用的 exactly-once 保护',
      '停放机制：闲置自动挂起、停放期零费用，可维持一支 Agent 舰队而不为静默付费；代价是账单这个传统故障信号被抹掉，官网未见任何存活监测或异常告警机制',
      '自带订阅：sky auth connect claude 调起 claude setup-token 绑定 Claude Pro/Max，connect chatgpt 需上传本地 Codex 登录态；绑定后符合条件的 Agent 模型侧零计费，但一旦 disconnect，跑在该订阅上的 Agent 会失败直到切回 Platform 计费',
      '开箱即用能力：网页抓取(Exa)、浏览器操作(TinyFish)、SERP 搜索(DataForSEO)、生图(gptimage)、去背景(rembg)、生视频(Seedance)、图生视频(MiniMax)、语音转写(Fish Audio) 及 Gmail/Notion/Slack 连接器，另接 2000+ 连接器',
      '开发者优先：npm i -g @agentsky/sky 装 CLI，sky launch 脚手架出声明式 agent.toml（可设 type/llm/capabilities/skills/customInstalls，vcpus 1|2|4|8）；API 统一在 /api/v1，发消息返回裸 202、输出走常驻 SSE 流，漏事件可从 events 端点重放并按 id 去重',
      '支持 Zero Data Retention（ZDR），secrets 写入后不可读回、静态加密；但独立评测站 VibeWatch 指出其公开证据不足，托管本身即让出控制权',
      '2026-08-03 登陆 Product Hunt 当日第一，由 Product Hunt CEO Rajiv Ayyangar 提名；各站抓取时点不同，票数记录在 371–469 之间，PH 上仅 1 条评价（5.00/5）',
      '中文生态零覆盖：无微信、钉钉、飞书、企业微信接入；自进化（Self-evolving）能力官网标注 coming soon，尚未上线'],
  },
  {
    id: 'browseros-neo',
    name: 'BrowserOS neo',
    description: '给Claude Code、Codex等Agent专用的本地浏览器，沿用你的Chrome登录态干活，全程可看可回放。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.0,
    url: 'https://www.browseros.com/neo',
    price: '完全免费、开源（AGPL-3.0）；软件本身不收费，模型侧沿用你自带的 API Key 或订阅，费用由所选模型厂商计',
    features: [
      '本身不含Agent：定位是给你已有的Agent当"手"，通过MCP被Claude Code / Claude Cowork / Codex / Cursor / VS Code / OpenClaw / Hermes 驱动',
      '一键导入Chrome登录态：Agent以你已登录的Gmail、GitHub、X等真实账号办事，绕开公开API够不到的登录墙',
      '第二浏览器定位：Agent只在自己的标签页里操作，不会关掉或抢走你正在写的文档标签，官方明确不替代Chrome',
      '驾驶舱视图：新标签页实时显示每个Agent在哪个站点、用哪个工具、走到第几步',
      '会话录像回放：每次运行存成可拖动进度条的视频，可倒回定位出错点再纠正指令',
      '省token：向Agent传递精简页面快照而非截图，官方称比Claude的Chrome扩展等方案更省token',
      '并行多Agent：可同时跑多个Agent，各自占用独立标签页组互不干扰',
      '本地优先：会话历史、截图、回放、设置均为本机磁盘文件，每个动作写入本地日志',
      '开源可审计：github.com/browseros-ai/BrowserOS，AGPL-3.0，Chromium 分支，主体 Felafax, Inc.',
      '2026-08-07 登陆 Product Hunt（209赞/16评论，当日第5），原名 BrowserClaw 因SEO更名',
      '仅支持 macOS 与 Windows，Linux 官方标注规划中；与面向真人使用的原版 BrowserOS 是两个产品，可并存',
      '安全须知：Agent共用你的登录态、per-agent配置隔离仅在路线图；官方文档提醒能访问其MCP端点者即可操控浏览器，勿公网暴露'],
  },
  {
    id: 'perplexity-computer',
    name: 'Perplexity Personal Computer',
    description: 'Perplexity的桌面Agent，在授权文件夹读写本地文件，云端调度20多个模型分派子任务。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 3.7,
    url: 'https://www.perplexity.ai/computer',
    price: 'Free $0 无 Computer；Pro $20/月（年付 $200，页面显示约 $17/月）含 500 Computer 额度/月，但不含桌面版 Personal Computer；Max $200/月（年付 $2,000，约 $167/月）含 10,000 额度/月，是解锁 Mac / Windows 桌面 Agent 的最低档；Enterprise Pro $40/席/月（年付 $400/席）；Enterprise Max $325/席/月（年付 $3,250/席）含桌面 Agent。额度当月清零不结转；自动续费默认关闭，默认月度加购上限 $200（即默认最大月支出 $400），可上调至 $2,000',
    features: [
      '官方定位 local agent harness（本地 Agent 工作台）：在经用户批准的本地文件夹内打开、读取、编辑文件，并调度子 Agent 连接应用与网页',
      '三层上下文合流：本地层（授权文件夹）+ 应用层（400+ 连接器，含 Word/Excel/PowerPoint/Outlook/OneDrive/Teams、Salesforce、Snowflake、HubSpot）+ 网络层（沿用 Perplexity 搜索与浏览）',
      '云脑本地手：AI 推理不在本机跑——本地应用只负责碰文件，任务分解与推理在 Perplexity 云端完成',
      '多模型元路由：2026-02 首发编排 19 个前沿模型、3 月起扩至 20+，默认主编排器为 Claude Opus 4.7，可切换 GPT-5.4 或 Claude Sonnet 4.6；分工为 Claude Opus 系核心推理 / Gemini 3 Pro 深度调研 / GPT-5.2 长上下文 / Grok 轻量快任务 / GPT-5.3-Codex 代码 / Nano Banana 出图 / Veo 3.1 视频。子 Agent 会自动管理依赖，缺数据时排队等待而非编造中间结果',
      '两个同名产品必须分清：云端版 Computer（2026-02-25 上线，跑在托管云沙箱，够不着本机文件，3 月起下放 Pro 档 500 额度/月）与桌面版 Personal Computer（2026-03-11 以 Mac mini 常驻形态宣布并开候补，4 月上 macOS，07-28 补齐 Windows 10/11，至今仅 Max / Enterprise Max 可用）',
      '沙箱规格：隔离 Linux 环境 2 vCPU / 8GB 内存，预装 Python、Node.js、ffmpeg 与标准 Unix 工具，Agent 可真实执行代码而非仅生成代码；单个任务可运行数小时',
      '四层架构：本地设备层 + 云端编排层 + 隔离执行沙箱（生成代码在沙箱跑）+ 独立云端浏览器 Comet 负责网页自动化（架构细节系独立研究者逆向归因，非厂商确认）',
      'Brain 持久记忆：把历史任务、文件与项目上下文带入新任务，跨会话延续',
      '安全护栏（厂商声明）：发邮件、删文件等敏感或难逆转操作需显式批准，每会话生成审计轨迹，并提供暂停 Agent 的终止开关',
      '产品线沿革：2026-02 首发云端版 Computer，04 月上 Mac，07-28 补齐 Windows 10/11 原生应用；发布前一周先落地 Office 侧边栏与 Teams 集成',
      '数据须知：文件读写在本机，但任务上下文（含本地文件信息、活跃应用）需经云端推理，非本地处理；Enterprise Max 合同默认不用于训练，消费级 Max 需手动退出',
      '安全争议：LayerX 研究称 Comet 浏览器在企业基准下比 Chrome 更易受钓鱼攻击；研究者另记录 AI 浏览器代理的"意图冲突"结构性漏洞（用户指令与攻击者网页内容可被合并为同一执行计划）',
      '额度机制是头号差评源：无每任务额度上限、无中途费用估算，静默失败（如 npm install 失败）会让 Agent 不停派生子 Agent 重试。Builder.io 评测中建一个基础网页遇部署问题即吃掉 10,000+ 额度（Max 整月配额），Reddit 重度日用者估算月度实付 $300-500；厂商已补上实时额度计数器',
      '独立实测数据：ai-tools-hub 一周实测——竞品调研 10 家出结构化报告 38 分钟耗月额度约 4%，三来源 ICP 分析 22 分钟约 2.5%，Streamlit 看板 1 小时 12 分约 6%；抽检五份报告约 100 条引用为 87 条准确 / 9 条部分正确 / 4 条编造',
      '独立评测短板：Zapier 实测自主网页导航脆弱且比人慢，站点 Cloudflare 与反爬会限流甚至困住 Agent，AI 生成音频判定 not ready for prime-time；Dania Accounting 称会计税务等细分技术议题产出不均需人工复核；早期采用者反馈 400+ 连接器脆弱，Vercel OAuth 令牌每会话过期',
      '口碑两面镜：Google Play 4.6 分 / 203 万评分 / 编辑推荐，Trustpilot 仅 1.5 分 / 707 条 / 82% 一星且几乎全为计费与退款争议',
      '信任背景（企业采购需自行掂量）：亚马逊 2026-03-10 获法院禁令阻止 Comet 抓取其数据；Cloudflare 记录其隐形爬虫规避禁抓指令；Reddit 与 Forbes 诉讼进行中；Doe v. Perplexity AI（3:26-cv-02803, N.D. Cal.）2026-03-31 提交、05-01 无偏见撤诉',
      '主要短板：$200/月价格门槛把最差异化的本地文件能力锁在高档位，且未公布降价时间表；微软 Copilot 约 $30/用户/月、原生握有 Microsoft Graph，AP 报道其付费席位在 2026 年 4-6 月季度已破 3000 万。另一层反讽是 Perplexity 2026-01 与微软 Azure 签下三年 7.5 亿美元 GPU 承诺，挑战 Copilot 的产品跑在微软云上'],
  },
  {
    id: 'annotate',
    name: 'Annotate',
    description: '录屏边画边说，把屏幕演示直接交给Cursor、Claude Code、Codex等Agent，本地处理不上传。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 3.8,
    url: 'https://xannotate.com',
    price: '完全免费、本地优先、无需登录；仅支持 macOS Apple Silicon（arm64），无付费档。安装包 DMG 由 annotate.canvas-vision.com 分发',
    features: [
      '屏幕录制即提示：录下屏幕操作，用画笔/矩形/文字指向具体 UI 元素，边说边讲要改什么，替代写长篇 prompt',
      '三步闭环：录制 → 边画边说 → 把会话交给 Agent，无需新建聊天窗口',
      '本地优先：画面帧与语音转录全部留在 Mac 本机，不上传、不登录、无云端依赖',
      'Agent 握手：通过本地打包的 annotate-session MCP server，把会话直接喂给 Cursor / Claude Code / Codex；Agent 读取关键帧+语音而非整段视频，省 token',
      '语音与画面时间轴对齐：说话被转录并精确对齐到当时屏幕帧，Agent 同时看到你指的按钮和你说的话',
      '多显示器一次录制：可同时捕获 app 在一屏、编辑器在另一屏，统一交付给 Agent',
      '免费与门槛：macOS Apple Silicon 免费下载、无需账号；需先安装启动一次使 MCP 包就位，且系统要有 Node.js',
      '发布信息：2026-08-06 登陆 Product Hunt，208 赞 / 19 评论，当日第 5；chatgate.ai、aat.ee、aipure.ai 多家独立站交叉确认',
      '局限：仅 macOS Apple Silicon，无官方 Windows / Linux；录制内容一旦交给本地 Agent，后续数据由该 Agent 的服务条款约束，涉及他人或敏感屏幕需先取得同意'],
  },
  {
    id: 'memmy-agent',
    name: 'Memmy Agent',
    description: '跨Agent共享记忆中枢+本地AI代理，让多个AI记住同一个你。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.0,
    url: 'https://memmy.bot',
    price: '免费起步赠 200 万 ChatGPT token；试用后切 BYOK 自带模型 Key；核心开源（MemTensor/memmy-agent）',
    features: [
      '跨Agent共享记忆：Claude Code、Cursor、Codex、OpenClaw、Hermes 共用同一本地记忆库，换工具不丢上下文',
      '三步闭环：扫描本机 AI 对话历史 → 去重归类成结构化长期记忆 → 按需把相关记忆注入当前任务，而非整库倾倒',
      '它自己也是 Agent：可直接交办"合并跨 Agent 的计划""把本周技术决策写成文档"等任务，不只会存记忆',
      '四层记忆架构（MemOS）：原始轨迹→行为策略→项目世界模型→可复用技能，越用越聪明而非越堆越乱',
      '本地优先：记忆默认存本机 SQLite，不上传云端；每次扫描需显式授权，可随时查看/删除任意记忆、关闭任意来源',
      '接入零摩擦：暴露 OpenAI 兼容本地 API（http://localhost:8765），任何能调 OpenAI 端点的工具都能用；另有桌面工作台/CLI/MCP/Skills，支持 Telegram·微信·飞书·钉钉',
      '模型与免费额度：支持 OpenAI/Anthropic/Gemini/DeepSeek/Ollama；注册赠 200 万 token，试用后 BYOK',
      '发布信息：2026-07-30 登陆 Product Hunt，534 赞 / 206 评论，当日第 2；GitHub MemTensor/memmy-agent 开源，chatgate.ai/byteiota/subagentic 等多家独立站评测'],
  },
  {
    id: 'agent-fm',
    name: 'Agent FM',
    description: 'Agent 指挥台：把多个 Claude Code/Codex 进度用语音+群聊实时播报与监管。',
    category: 'AI工作台',
    subCategory: '桌面智能体',
    rating: 4.0,
    url: 'https://agentfm.ai',
    price: 'YC S26 批次项目，当前 beta 免费试用、正式定价未公开；桌面应用 macOS 优先，语音转写层已覆盖 Mac/Windows',
    features: [
      'Agent 指挥台：一个群聊界面统一收听并调度你所有 Claude Code / Codex / OpenCode 会话，告别多终端肉眼盯',
      '实时语音播报：把 Agent 的进度、阻塞点、假设与决策转成 ambient 音频流，不盯屏幕也能听见"谁跑偏了"',
      '群聊式干预：Agent 主动汇报，你直接在聊天里回指令纠偏，把"被动监视"变成"异步协作"',
      '可观测性面板：跨模型供应商统计活跃时长、token 消耗、模型占比、工具失败率，揪出烧 token/卡死的 Agent',
      '计算机操作（Computer Use）：直接在机器上跑审计、存结果；语音转写（Voice-to-Text）系统级随处可用，Mac/Windows 均支持',
      '本地与远程工作区都支持；被动监听独立进程，不代理、不干扰你的 Agent，零减速',
      '发布与背书：YC S26 批次；创始人来自 Meta 超级智能实验室与 Snowflake；官网称 410+ 工程师在用、60+ 付费、12 万+ 次语音播报',
      '定位差异：它不是又一个 coding harness，而是坐在 Claude Code/Codex 之上的"监工"——库内桌面智能体都在"自己干活"，Agent FM 专管"别人干得怎么样"'],
  },
]
